export const TEMP = "TEMP";

export const FETCH_POSTS_START = "FETCH_POSTS_START";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";

export const GET_POST_START = "GET_POST_START";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAIL = "GET_POST_FAIL";

export const GET_FACULTATIES_START = "GET_FACULTATIES_START";
export const GET_FACULTATIES_SUCCESS = "GET_FACULTATIES_SUCCESS";
export const GET_FACULTATIES_FAIL = "GET_FACULTATIES_FAIL";

export const GET_COURSE_START = "GET_COURSE_START";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const GET_COURSE_FAIL = "GET_COURSE_FAIL";

export const GET_GROUP_START = "GET_GROUP_START";
export const GET_GROUP_SUCCESS = "GET_GROUP_SUCCESS";
export const GET_GROUP_FAIL = "GET_GROUP_FAIL";
